version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hello-world-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro
    environment:
      - PYTHONUNBUFFERED=1
      - RELOAD=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - hello-world-network

  frontend:
    image: node:20-alpine
    container_name: hello-world-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge
    name: hello-world-network-dev
